using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ObstaclePathing : MonoBehaviour
{

    [SerializeField] List<Transform> waypoints;

    [SerializeField] WaveConfig waveConfig;

  
    int waypointIndex = 0;

    void Start()
    {

        waypoints = waveConfig.GetWaypoints();

        transform.position = waypoints[waypointIndex].transform.position;


    }

    void Update()
    {
        ObstacleMove();
    }

    private void ObstacleMove()
    {

        if (waypointIndex <= waypoints.Count - 1)
        {

            var targetPosition = waypoints[waypointIndex].transform.position;

        
            targetPosition.z = 0f;

            var obstacleMovement = waveConfig.GetObstacleMoveSpeed() * Time.deltaTime;

            
            transform.position = Vector2.MoveTowards(transform.position, targetPosition, obstacleMovement);


            if (transform.position == targetPosition)
            {
                waypointIndex++;
            }

        }

        else
        {

            Destroy(gameObject);
        }
    }


    public void SetWaveConfig(WaveConfig waveConfigToSet)
    {
        waveConfig = waveConfigToSet;
    }


}
